Authorize.Host/Controllers/ApiSourceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Authorize.Application.ApiSource;
using Authorize.Application.ApiSource.Model;
using Authorize.Host.App_Data;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace Authorize.Host.Controllers
{
    public class ApiSourceController : Controller
    {
        private readonly IApiSourceService _service;

        public ApiSourceController()
        {
            _service = new ApiSourceService();
        }

        // GET: ApiSource
        public ActionResult Index()
        {
            var list = _service.GetList();
            return View(list);
        }

        // GET: ApiSource/Details/5
        public ActionResult Details(Guid id)
        {
            var model = _service.Get(id);
            return View(model);
        }

        // GET: ApiSource/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ApiSource/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ApiSourceInputModel model)
        {
            try
            {
                _service.Create(model);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: ApiSource/Edit/5
        public ActionResult Edit(Guid id)
        {
            var model = _service.Get(id);
            return View(model);
        }

        // POST: ApiSource/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(ApiSourceModel model)
        {
            try
            {
                _service.Modify(model);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: ApiSource/Delete/5
        public ActionResult Delete(Guid id)
        {
            var model = _service.Get(id);
            return View(model);
        }

        // POST: ApiSource/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(Guid id, IFormCollection collection)
        {
            try
            {
                _service.Delete(id);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Authorize.Host/Controllers/ClientSourceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Authorize.Application.ClientSource;
using Authorize.Application.ClientSource.Model;
using Authorize.Host.App_Data;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace Authorize.Host.Controllers
{
    public class ClientSourceController : Controller
    {
        private readonly IClientSourceService _service;
        public ClientSourceController()
        {
            _service = new ClientSourceService();
        }
        // GET: ClientSource
        public ActionResult Index()
        {
            var modelList = _service.GetList();
            return View(modelList);
        }

        // GET: ClientSource/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: ClientSource/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ClientSource/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ClientSourceInputModel model)
        {
            try
            {
                _service.Create(model);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View(model);
            }
        }

        // GET: ClientSource/Edit/5
        public ActionResult Edit(Guid id)
        {
            var model = _service.Get(id);
            return View(model);
        }

        // POST: ClientSource/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(ClientSourceModel model)
        {
            try
            {
                _service.Modify(model);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: ClientSource/Delete/5
        public ActionResult Delete(Guid id)
        {
            var model = _service.Get(id);
            return View(model);
        }

        // POST: ClientSource/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(Guid id, IFormCollection collection)
        {
            try
            {
                _service.Delete(id);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Authorize.Host/Views/Shared/_Layout.cshtml
@using IdentityServer4.Extensions
@{
    string name = null;
    if (!true.Equals(ViewData["signed-out"]))
    {
        name = Context.User?.GetDisplayName();
    }
}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>IdentityServer4</title>
    <link rel="icon" type="image/x-icon" href="~/favicon.ico" />
    <link rel="shortcut icon" type="image/x-icon" href="~/favicon.ico" />
    <link rel="stylesheet" href="~/lib/bootstrap/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="~/">
                    <span class="navbar-brand">
                        <img src="~/icon.png" class="icon-banner">
                        Dolphin Authorize
                    </span>
                </a>
            </div>
            <div class="collapse navbar-collapse">
                <ul class="nav navbar-nav">
                    <li>
                        @Html.ActionLink("客户端列表", "Index", "ClientSource")
                    </li>
                    <li>
                        @Html.ActionLink("Api资源", "Index", "ApiSource")
                    </li>
                </ul>
                @if (!string.IsNullOrWhiteSpace(name))
    {
            <ul class="nav navbar-nav navbar-right">
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">@name <b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <li><a asp-action="Logout" asp-controller="Account">注销</a></li>
                    </ul>
                </li>
            </ul>
}
            </div>

        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
    </div>

    <script src="~/lib/jquery/jquery.js"></script>
    <script src="~/lib/bootstrap/js/bootstrap.js"></script>
    <script src="~/lib/jweixin-1.2.0.js" type="text/javascript"></script>
    @RenderSection("scripts", required: false)
</body>
</html>

Authorize.Host/Views/Shared/_ValidationSummary.cshtml
@if (ViewContext.ModelState.IsValid == false)
{
    <div class="alert alert-danger">
        <strong>Error</strong>
        <div asp-validation-summary="All" class="danger"></div>
    </div>
}